// ============================================================================
// BMC SoC — Top-Level Integration
// ============================================================================
// Instantiates and wires together:
//   - VeeR EL2 Core (el2_veer_wrapper)
//   - AXI4-to-Wishbone Bridge
//   - Wishbone Interconnect (7-slave decoder)
//   - Standard peripherals: UART, Timer, GPIO
//   - Custom IPs: Heartbeat Monitor, Power/Reset Sequencer, Recovery Policy
//   - Optional: VGA Controller
//
// Memory Map:
//   0x0000_0000 – 0x0000_FFFF  Instruction Memory (ICCM, inside VeeR)
//   0x0001_0000 – 0x0001_FFFF  Data Memory (DCCM, inside VeeR)
//   0x0002_0000 – 0x0002_00FF  UART
//   0x0002_0100 – 0x0002_01FF  Timer
//   0x0002_0200 – 0x0002_02FF  GPIO
//   0x0002_0300 – 0x0002_03FF  Heartbeat Monitor
//   0x0002_0400 – 0x0002_04FF  Power/Reset Sequencer
//   0x0002_0500 – 0x0002_05FF  Recovery Policy / Event Log
//   0x0002_0600 – 0x0002_06FF  VGA Controller
// ============================================================================

module soc_top (
    input  wire        clk,
    input  wire        rst_n,

    // ---- External Signals ----
    // Heartbeat from simulated main system
    input  wire        heartbeat_in,
    // Reset command to simulated main system
    output wire        reset_out,

    // UART
    input  wire        uart_rx,
    output wire        uart_tx,

    // JTAG Debug (directly to VeeR core)
    input  wire        jtag_tck,
    input  wire        jtag_tms,
    input  wire        jtag_tdi,
    output wire        jtag_tdo,

    // VGA (optional)
    output wire        vga_hsync,
    output wire        vga_vsync,
    output wire [11:0] vga_rgb
);

    // ========================================================================
    // Internal Signals
    // ========================================================================

    // Active-high reset derived from active-low rst_n
    wire rst = ~rst_n;

    // ---- AXI4 bus signals (VeeR LSU/SB master → bridge) ----
    // Write Address Channel
    wire [31:0] axi_awaddr;
    wire [2:0]  axi_awprot;
    wire        axi_awvalid;
    wire        axi_awready;
    // Write Data Channel
    wire [31:0] axi_wdata;
    wire [3:0]  axi_wstrb;
    wire        axi_wvalid;
    wire        axi_wready;
    // Write Response Channel
    wire [1:0]  axi_bresp;
    wire        axi_bvalid;
    wire        axi_bready;
    // Read Address Channel
    wire [31:0] axi_araddr;
    wire [2:0]  axi_arprot;
    wire        axi_arvalid;
    wire        axi_arready;
    // Read Data Channel
    wire [31:0] axi_rdata;
    wire [1:0]  axi_rresp;
    wire        axi_rvalid;
    wire        axi_rready;

    // ---- Wishbone master bus (bridge → interconnect) ----
    wire [31:0] wbm_adr;
    wire [31:0] wbm_dat_m2s;   // Master to slave (write data)
    wire [31:0] wbm_dat_s2m;   // Slave to master (read data)
    wire        wbm_we;
    wire [3:0]  wbm_sel;
    wire        wbm_stb;
    wire        wbm_cyc;
    wire        wbm_ack;
    wire        wbm_err;

    // ---- Wishbone slave interfaces (interconnect → peripherals) ----
    // Slave 0: UART
    wire [7:0]  wbs0_adr;
    wire [31:0] wbs0_dat_o, wbs0_dat_i;
    wire        wbs0_we, wbs0_stb, wbs0_cyc, wbs0_ack;
    wire [3:0]  wbs0_sel;
    // Slave 1: Timer
    wire [7:0]  wbs1_adr;
    wire [31:0] wbs1_dat_o, wbs1_dat_i;
    wire        wbs1_we, wbs1_stb, wbs1_cyc, wbs1_ack;
    wire [3:0]  wbs1_sel;
    // Slave 2: GPIO
    wire [7:0]  wbs2_adr;
    wire [31:0] wbs2_dat_o, wbs2_dat_i;
    wire        wbs2_we, wbs2_stb, wbs2_cyc, wbs2_ack;
    wire [3:0]  wbs2_sel;
    // Slave 3: Heartbeat Monitor
    wire [7:0]  wbs3_adr;
    wire [31:0] wbs3_dat_o, wbs3_dat_i;
    wire        wbs3_we, wbs3_stb, wbs3_cyc, wbs3_ack;
    wire [3:0]  wbs3_sel;
    // Slave 4: Reset Sequencer
    wire [7:0]  wbs4_adr;
    wire [31:0] wbs4_dat_o, wbs4_dat_i;
    wire        wbs4_we, wbs4_stb, wbs4_cyc, wbs4_ack;
    wire [3:0]  wbs4_sel;
    // Slave 5: Recovery Policy
    wire [7:0]  wbs5_adr;
    wire [31:0] wbs5_dat_o, wbs5_dat_i;
    wire        wbs5_we, wbs5_stb, wbs5_cyc, wbs5_ack;
    wire [3:0]  wbs5_sel;
    // Slave 6: VGA Controller
    wire [7:0]  wbs6_adr;
    wire [31:0] wbs6_dat_o, wbs6_dat_i;
    wire        wbs6_we, wbs6_stb, wbs6_cyc, wbs6_ack;
    wire [3:0]  wbs6_sel;

    // ---- Point-to-point inter-IP signals ----
    wire        hb_irq;            // Heartbeat Monitor → PIC (optional)
    wire        reset_out_internal; // Reset Sequencer → GPIO output

    // ========================================================================
    // VeeR EL2 Core
    // ========================================================================
    // NOTE: The actual VeeR EL2 instantiation depends on the specific
    // configuration generated by the VeeR config tool. The AXI master
    // interface signals from the LSU (Load/Store Unit) system bus port
    // are connected to the AXI-to-Wishbone bridge for peripheral access.
    //
    // The core's ICCM and DCCM are internal to el2_veer_wrapper and handle
    // instruction fetch and data memory directly via tightly-coupled paths.
    //
    // For the peripheral bus, we use the System Bus (SB) AXI master port,
    // which the core uses for non-TCM address ranges.
    //
    // TODO: Instantiate el2_veer_wrapper with proper parameter configuration.
    //       The SB AXI master signals (sb_axi_*) connect to the bridge.
    //       Interrupt input: extintsrc_req[1] <= hb_irq (optional)

    // ========================================================================
    // Placeholder: VeeR EL2 Core Instance
    // ========================================================================
    // In a full build, this would be:
    //
    //   el2_veer_wrapper #(.parameters...) u_veer (
    //       .clk           (clk),
    //       .rst_l         (rst_n),
    //       .dbg_rst_l     (rst_n),
    //       // SB AXI master → peripheral bus
    //       .sb_axi_awaddr (axi_awaddr),
    //       .sb_axi_awvalid(axi_awvalid),
    //       .sb_axi_awready(axi_awready),
    //       .sb_axi_wdata  (axi_wdata),
    //       .sb_axi_wstrb  (axi_wstrb),
    //       .sb_axi_wvalid (axi_wvalid),
    //       .sb_axi_wready (axi_wready),
    //       .sb_axi_bresp  (axi_bresp),
    //       .sb_axi_bvalid (axi_bvalid),
    //       .sb_axi_bready (axi_bready),
    //       .sb_axi_araddr (axi_araddr),
    //       .sb_axi_arvalid(axi_arvalid),
    //       .sb_axi_arready(axi_arready),
    //       .sb_axi_rdata  (axi_rdata),
    //       .sb_axi_rresp  (axi_rresp),
    //       .sb_axi_rvalid (axi_rvalid),
    //       .sb_axi_rready (axi_rready),
    //       // JTAG
    //       .jtag_tck      (jtag_tck),
    //       .jtag_tms      (jtag_tms),
    //       .jtag_tdi      (jtag_tdi),
    //       .jtag_tdo      (jtag_tdo),
    //       // Interrupts
    //       .extintsrc_req ({...hb_irq...}),
    //       ...
    //   );

    // ========================================================================
    // AXI4-Lite to Wishbone Bridge
    // ========================================================================
    axi4_to_wb_bridge u_axi2wb (
        .clk            (clk),
        .rst_n          (rst_n),

        // AXI4-Lite slave (from VeeR SB master)
        .s_axi_awaddr   (axi_awaddr),
        .s_axi_awprot   (axi_awprot),
        .s_axi_awvalid  (axi_awvalid),
        .s_axi_awready  (axi_awready),
        .s_axi_wdata    (axi_wdata),
        .s_axi_wstrb    (axi_wstrb),
        .s_axi_wvalid   (axi_wvalid),
        .s_axi_wready   (axi_wready),
        .s_axi_bresp    (axi_bresp),
        .s_axi_bvalid   (axi_bvalid),
        .s_axi_bready   (axi_bready),
        .s_axi_araddr   (axi_araddr),
        .s_axi_arprot   (axi_arprot),
        .s_axi_arvalid  (axi_arvalid),
        .s_axi_arready  (axi_arready),
        .s_axi_rdata    (axi_rdata),
        .s_axi_rresp    (axi_rresp),
        .s_axi_rvalid   (axi_rvalid),
        .s_axi_rready   (axi_rready),

        // Wishbone master (to interconnect)
        .wb_adr_o       (wbm_adr),
        .wb_dat_o       (wbm_dat_m2s),
        .wb_dat_i       (wbm_dat_s2m),
        .wb_we_o        (wbm_we),
        .wb_sel_o       (wbm_sel),
        .wb_stb_o       (wbm_stb),
        .wb_cyc_o       (wbm_cyc),
        .wb_ack_i       (wbm_ack),
        .wb_err_i       (wbm_err)
    );

    // ========================================================================
    // Wishbone Interconnect (1 master → 7 slaves)
    // ========================================================================
    wb_interconnect u_wb_intercon (
        // Master side
        .wbm_adr_i      (wbm_adr),
        .wbm_dat_i      (wbm_dat_m2s),
        .wbm_dat_o      (wbm_dat_s2m),
        .wbm_we_i       (wbm_we),
        .wbm_sel_i      (wbm_sel),
        .wbm_stb_i      (wbm_stb),
        .wbm_cyc_i      (wbm_cyc),
        .wbm_ack_o      (wbm_ack),
        .wbm_err_o      (wbm_err),

        // Slave 0: UART
        .wbs0_adr_o     (wbs0_adr),
        .wbs0_dat_o     (wbs0_dat_o),
        .wbs0_dat_i     (wbs0_dat_i),
        .wbs0_we_o      (wbs0_we),
        .wbs0_sel_o     (wbs0_sel),
        .wbs0_stb_o     (wbs0_stb),
        .wbs0_cyc_o     (wbs0_cyc),
        .wbs0_ack_i     (wbs0_ack),

        // Slave 1: Timer
        .wbs1_adr_o     (wbs1_adr),
        .wbs1_dat_o     (wbs1_dat_o),
        .wbs1_dat_i     (wbs1_dat_i),
        .wbs1_we_o      (wbs1_we),
        .wbs1_sel_o     (wbs1_sel),
        .wbs1_stb_o     (wbs1_stb),
        .wbs1_cyc_o     (wbs1_cyc),
        .wbs1_ack_i     (wbs1_ack),

        // Slave 2: GPIO
        .wbs2_adr_o     (wbs2_adr),
        .wbs2_dat_o     (wbs2_dat_o),
        .wbs2_dat_i     (wbs2_dat_i),
        .wbs2_we_o      (wbs2_we),
        .wbs2_sel_o     (wbs2_sel),
        .wbs2_stb_o     (wbs2_stb),
        .wbs2_cyc_o     (wbs2_cyc),
        .wbs2_ack_i     (wbs2_ack),

        // Slave 3: Heartbeat Monitor
        .wbs3_adr_o     (wbs3_adr),
        .wbs3_dat_o     (wbs3_dat_o),
        .wbs3_dat_i     (wbs3_dat_i),
        .wbs3_we_o      (wbs3_we),
        .wbs3_sel_o     (wbs3_sel),
        .wbs3_stb_o     (wbs3_stb),
        .wbs3_cyc_o     (wbs3_cyc),
        .wbs3_ack_i     (wbs3_ack),

        // Slave 4: Reset Sequencer
        .wbs4_adr_o     (wbs4_adr),
        .wbs4_dat_o     (wbs4_dat_o),
        .wbs4_dat_i     (wbs4_dat_i),
        .wbs4_we_o      (wbs4_we),
        .wbs4_sel_o     (wbs4_sel),
        .wbs4_stb_o     (wbs4_stb),
        .wbs4_cyc_o     (wbs4_cyc),
        .wbs4_ack_i     (wbs4_ack),

        // Slave 5: Recovery Policy
        .wbs5_adr_o     (wbs5_adr),
        .wbs5_dat_o     (wbs5_dat_o),
        .wbs5_dat_i     (wbs5_dat_i),
        .wbs5_we_o      (wbs5_we),
        .wbs5_sel_o     (wbs5_sel),
        .wbs5_stb_o     (wbs5_stb),
        .wbs5_cyc_o     (wbs5_cyc),
        .wbs5_ack_i     (wbs5_ack),

        // Slave 6: VGA Controller
        .wbs6_adr_o     (wbs6_adr),
        .wbs6_dat_o     (wbs6_dat_o),
        .wbs6_dat_i     (wbs6_dat_i),
        .wbs6_we_o      (wbs6_we),
        .wbs6_sel_o     (wbs6_sel),
        .wbs6_stb_o     (wbs6_stb),
        .wbs6_cyc_o     (wbs6_cyc),
        .wbs6_ack_i     (wbs6_ack)
    );

    // ========================================================================
    // Slave 0: UART Peripheral (Pre-built)
    // ========================================================================
    // TODO: Instantiate pre-built Wishbone UART core.
    // For now, stub with default responses.
    assign wbs0_dat_i = 32'd0;
    assign wbs0_ack   = wbs0_stb & wbs0_cyc;

    // UART TX/RX external connections
    // assign uart_tx = uart_core_tx;
    assign uart_tx = 1'b1;  // Idle high (stub)

    // ========================================================================
    // Slave 1: Timer Peripheral (Pre-built)
    // ========================================================================
    // TODO: Instantiate pre-built Wishbone Timer core.
    // For now, stub with a simple free-running counter.
    reg [31:0] timer_counter;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            timer_counter <= 32'd0;
        else
            timer_counter <= timer_counter + 32'd1;
    end

    // Timer stub: reads return counter value
    assign wbs1_dat_i = timer_counter;
    assign wbs1_ack   = wbs1_stb & wbs1_cyc;

    // ========================================================================
    // Slave 2: GPIO Peripheral (Pre-built)
    // ========================================================================
    // TODO: Instantiate pre-built Wishbone GPIO core.
    // For now, stub — heartbeat_in and reset_out are wired directly.
    assign wbs2_dat_i = {30'd0, reset_out_internal, heartbeat_in};
    assign wbs2_ack   = wbs2_stb & wbs2_cyc;

    // ========================================================================
    // Slave 3: Heartbeat Monitor (Custom IP #1)
    // ========================================================================
    heartbeat_monitor u_heartbeat (
        .wb_clk_i     (clk),
        .wb_rst_i     (rst),
        .wb_adr_i     (wbs3_adr),
        .wb_dat_i     (wbs3_dat_o),    // Interconnect dat_o → slave dat_i
        .wb_dat_o     (wbs3_dat_i),    // Slave dat_o → interconnect dat_i
        .wb_we_i      (wbs3_we),
        .wb_sel_i     (wbs3_sel),
        .wb_stb_i     (wbs3_stb),
        .wb_cyc_i     (wbs3_cyc),
        .wb_ack_o     (wbs3_ack),
        .heartbeat_in (heartbeat_in),  // Direct wire from external pad
        .hb_irq       (hb_irq)
    );

    // ========================================================================
    // Slave 4: Power/Reset Sequencer (Custom IP #2)
    // ========================================================================
    reset_sequencer u_reset_seq (
        .wb_clk_i     (clk),
        .wb_rst_i     (rst),
        .wb_adr_i     (wbs4_adr),
        .wb_dat_i     (wbs4_dat_o),
        .wb_dat_o     (wbs4_dat_i),
        .wb_we_i      (wbs4_we),
        .wb_sel_i     (wbs4_sel),
        .wb_stb_i     (wbs4_stb),
        .wb_cyc_i     (wbs4_cyc),
        .wb_ack_o     (wbs4_ack),
        .reset_out    (reset_out_internal)
    );

    // Reset output to external pad
    assign reset_out = reset_out_internal;

    // ========================================================================
    // Slave 5: Recovery Policy & Event Log (Custom IP #3)
    // ========================================================================
    recovery_policy u_rec_policy (
        .wb_clk_i     (clk),
        .wb_rst_i     (rst),
        .wb_adr_i     (wbs5_adr),
        .wb_dat_i     (wbs5_dat_o),
        .wb_dat_o     (wbs5_dat_i),
        .wb_we_i      (wbs5_we),
        .wb_sel_i     (wbs5_sel),
        .wb_stb_i     (wbs5_stb),
        .wb_cyc_i     (wbs5_cyc),
        .wb_ack_o     (wbs5_ack)
    );

    // ========================================================================
    // Slave 6: VGA Controller (Custom IP #4, Optional)
    // ========================================================================
    vga_controller u_vga (
        .wb_clk_i     (clk),
        .wb_rst_i     (rst),
        .wb_adr_i     (wbs6_adr),
        .wb_dat_i     (wbs6_dat_o),
        .wb_dat_o     (wbs6_dat_i),
        .wb_we_i      (wbs6_we),
        .wb_sel_i     (wbs6_sel),
        .wb_stb_i     (wbs6_stb),
        .wb_cyc_i     (wbs6_cyc),
        .wb_ack_o     (wbs6_ack),
        .vga_hsync    (vga_hsync),
        .vga_vsync    (vga_vsync),
        .vga_rgb      (vga_rgb)
    );

    // ========================================================================
    // JTAG Stub (directly connected to VeeR core when instantiated)
    // ========================================================================
    assign jtag_tdo = 1'b0;  // Stub — replaced by core connection

endmodule
